"""
Django settings for myapp project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b)d5d0ht#79_lx%d_q!p_966p3a1%va7=!f@vqp4i$)a_cz#s1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'polls.apps.PollsConfig',  #自作アプリの登録
    #自作アプリの登録ができたら、以下のコマンドでマイグレーションする。
    #  python manage.py makemigrations polls
    'django.contrib.admin',  #管理サイト
    'django.contrib.auth',  #承認システム
    'django.contrib.contenttypes',  #コンテンツタイプフレームワーク
    'django.contrib.sessions',  #セッションフレームワーク
    'django.contrib.messages',  #メッセージフレームワーク
    'django.contrib.staticfiles',  #静的ファイルの管理フレームワーク
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
######################################################################################################
#Data Baseの設定に関する部分
#DBの設定に関して、SQLiteを使用している場合は、自動生成される。
#MySQL,PostgreSQLに関しては、以下のコマンドをたたいて環境の作成を行う。
# CREATE DATABASE database_name;
#
#Tableの作成は、以下のコマンドで行う。(defaultの状態でも必ず最初に行う。)
# python manage.py migrate　<-めっちゃ重要 #####################################################################
#上記のコマンドは、INSTALLED_APPSのアプリについてのTableが作成される。
######################################################################################################
#SQLiteについて
#sqlite databe_name <-データベースに入る
#.tables <-テーブル一覧を見る
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', #Engine Name
        'NAME': BASE_DIR / 'db.sqlite3', #DB Name
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

######################################################################################################
# 以下の設定に注意
######################################################################################################
LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'
######################################################################################################
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
